// <auto-generated />
using System;
using Djl.EventDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Djl.EventDbContext.Web.Test.Migrations
{
    [DbContext(typeof(MqEventDbcontext))]
    [Migration("20180702025800_InitDb")]
    partial class InitDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Djl.EventDbContext.Core.MqEventMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AssemblyName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ClassFullName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatiedDateTime");

                    b.Property<string>("JsonBody")
                        .IsRequired()
                        .HasMaxLength(4000);

                    b.Property<string>("PublishErrorMsg")
                        .HasMaxLength(1000);

                    b.Property<int>("RetryCount");

                    b.Property<DateTime?>("SeedTime");

                    b.HasKey("Id");

                    b.ToTable("MqEventMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
